import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { test } from 'node:test';
const storage = new Map();
globalThis.localStorage = { getItem: key => storage.get(key) ?? null, setItem: (key, value) => storage.set(key, String(value)), removeItem: key => storage.delete(key) };
globalThis.window = { dispatchEvent() {}, location: { reload() {} } };
const data = await readFile(new URL('../src/data.js', import.meta.url), 'utf8');
const dataUrl = 'data:text/javascript;base64,' + Buffer.from(data).toString('base64');
const source = (await readFile(new URL('../src/demo.js', import.meta.url), 'utf8')).replace('"./data.js"', JSON.stringify(dataUrl)).replace('import.meta.env.VITE_DEMO_MODE', '"true"');
const { demo, resetDemo } = await import('data:text/javascript;base64,' + Buffer.from(source).toString('base64'));
test('catalog, borrowing, returns, wishlist, profile and reset work without network', () => {
  globalThis.fetch = () => { throw new Error('Demo must not contact a server'); };
  assert.equal(demo.fetchBooks().length, 6);
  const before = demo.fetchBooks().find(b => b.id === 3).copies;
  const record = demo.borrowBook(1, 3);
  assert.equal(demo.fetchBooks().find(b => b.id === 3).copies, before - 1);
  assert.throws(() => demo.borrowBook(1, 3), /already borrowed/);
  demo.returnBook(record.id);
  assert.equal(demo.fetchBooks().find(b => b.id === 3).copies, before);
  assert.throws(() => demo.returnBook(record.id), /no longer active/);
  demo.addToWishlist(1, 3); demo.addToWishlist(1, 3);
  assert.equal(demo.getWishlist().filter(b => b.id === 3).length, 1);
  demo.removeFromWishlist(1, 3);
  assert.equal(demo.checkWishlisted(1, 3), false);
  demo.updateUser(1, { name: 'Test Reader' });
  assert.equal(demo.getUser().name, 'Test Reader');
  assert.throws(() => demo.deleteBook(1), /history/);
  const added = demo.addBook({ title: 'Demo Book', author: 'Sample Author', availableCopies: 2 });
  assert.equal(demo.fetchBooks().length, 7);
  demo.deleteBook(added.id);
  assert.equal(demo.fetchBooks().length, 6);
  resetDemo();
  assert.equal(demo.getUser().name, 'Demo Reader');
  assert.equal(demo.getMyBooks().length, 1);
  assert.equal(demo.getFines()[0].amount, 40);
});
