export const NAV_LINKS = ["Home", "Books", "My Books", "Wishlist", "Borrow History", "Fines", "Profile"];

export const BOOKS = [
  {
    title: "Atomic Habits",
    author: "James Clear",
    category: "Self Help",
    status: "Available",
    bg: "#F3ECD8",
    accent: "#C89B3C",
    sub: "An Easy & Proven Way to Build Good Habits & Break Bad Ones",
    tagline: "Tiny Changes, Remarkable Results",
    rating: 4.8,
    ratingCount: 2345,
    copies: 12,
    publisher: "Penguin Random House",
    language: "English",
    pages: 320,
    isbn: "978-0735211292",
    borrowDuration: 14,
    lateFine: 10,
    description:
      "No matter your goals, Atomic Habits offers a proven framework for improving every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
    takeaways: [
      "Make time for new habits (even when life gets crazy)",
      "Overcome a lack of motivation and willpower",
      "Design your environment to make success easier",
      "Get back on track when you fall off course",
    ],
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    category: "Fiction",
    status: "Available",
    bg: "linear-gradient(160deg,#C1512D,#8B3A1E)",
    accent: "#F3D9A4",
    sub: null,
    tagline: "A fable about following your dream",
    rating: 4.7,
    ratingCount: 5210,
    copies: 8,
    publisher: "HarperOne",
    language: "English",
    pages: 208,
    isbn: "978-0062315007",
    borrowDuration: 14,
    lateFine: 10,
    description:
      "Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure as extravagant as any ever found.",
    takeaways: [
      "Listen to your heart and personal legend",
      "Every search begins with beginner's luck",
      "Fear of failure is the biggest obstacle to a dream",
      "The universe conspires to help those who pursue their purpose",
    ],
    dark: true,
  },
  {
    title: "Deep Work",
    author: "Cal Newport",
    category: "Productivity",
    status: "Available",
    bg: "#EFE9DA",
    accent: "#2E2E2E",
    sub: "Rules for Focused Success in a Distracted World",
    tagline: "Rules for Focused Success in a Distracted World",
    rating: 4.6,
    ratingCount: 3110,
    copies: 6,
    publisher: "Grand Central Publishing",
    language: "English",
    pages: 296,
    isbn: "978-1455586691",
    borrowDuration: 14,
    lateFine: 10,
    description:
      "Cal Newport argues that the ability to focus without distraction is becoming increasingly valuable, and that most people have lost the ability to go deep, spending their days instead in a frantic blur of email and social media.",
    takeaways: [
      "Deep work is the ability to focus without distraction",
      "Schedule every minute of your day",
      "Embrace boredom to strengthen your focus muscle",
      "Quit social media if it doesn't serve your goals",
    ],
  },
  {
    title: "Ikigai",
    author: "Hector Garcia",
    category: "Self Help",
    status: "Available",
    bg: "#D7E4EC",
    accent: "#2E2E2E",
    sub: "The Japanese Secret to a Long and Happy Life",
    tagline: "The Japanese Secret to a Long and Happy Life",
    rating: 4.5,
    ratingCount: 1980,
    copies: 10,
    publisher: "Penguin Life",
    language: "English",
    pages: 208,
    isbn: "978-0143130727",
    borrowDuration: 14,
    lateFine: 10,
    description:
      "Ikigai reveals the Japanese secret to a long and happy life, exploring the lifestyle habits of the residents of the island with the most centenarians in the world.",
    takeaways: [
      "Find your reason for being",
      "Stay active and never fully retire",
      "Eat until you're 80% full",
      "Surround yourself with good friends",
    ],
  },
  {
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    category: "Personal Development",
    status: "Available",
    bg: "linear-gradient(160deg,#2F3B24,#1D2417)",
    accent: "#D9A441",
    sub: "The Original Version, Restored and Revised",
    tagline: "The Original Version, Restored and Revised",
    rating: 4.6,
    ratingCount: 4210,
    copies: 5,
    publisher: "TarcherPerigee",
    language: "English",
    pages: 384,
    isbn: "978-1585424337",
    borrowDuration: 14,
    lateFine: 10,
    description:
      "Napoleon Hill's classic distills the traits and habits shared by hundreds of self-made millionaires he studied over twenty years, into thirteen steps toward wealth and success.",
    takeaways: [
      "Desire is the starting point of all achievement",
      "Faith and persistence overcome failure",
      "Specialized knowledge compounds over time",
      "A mastermind group accelerates results",
    ],
    dark: true,
  },
  {
    title: "The Psychology of Money",
    author: "Morgan Housel",
    category: "Finance",
    status: "Available",
    bg: "#F1EFE4",
    accent: "#4C5B3A",
    sub: "Timeless lessons on Wealth, Greed, and Happiness",
    tagline: "Timeless lessons on Wealth, Greed, and Happiness",
    rating: 4.7,
    ratingCount: 2890,
    copies: 9,
    publisher: "Harriman House",
    language: "English",
    pages: 256,
    isbn: "978-0857197689",
    borrowDuration: 14,
    lateFine: 10,
    description:
      "Morgan Housel explores the strange ways people think about money and teaches you how to make better sense of one of life's most important topics through eighteen short stories.",
    takeaways: [
      "Doing well with money has little to do with intelligence",
      "Compounding rewards patience over brilliance",
      "Save without a specific goal in mind",
      "Room for error is the most underappreciated asset",
    ],
  },
];

export const CATEGORIES = ["All Categories", "Self Help", "Fiction", "Productivity", "Personal Development", "Finance"];
export const AUTHORS = ["All Authors", "James Clear", "Paulo Coelho", "Cal Newport", "Hector Garcia", "Napoleon Hill", "Morgan Housel"];

/* ---------- Admin dashboard mock data ---------- */

export const ADMIN_STATS = [
  { label: "Total Books", value: "1,250", icon: "BookMarked", bg: "#5B6B2E" },
  { label: "Available Books", value: "980", icon: "BookOpen", bg: "#DCE6C4" },
  { label: "Total Users", value: "320", icon: "Users", bg: "#F0E2B6" },
  { label: "Borrowed Books", value: "270", icon: "ArrowLeftRight", bg: "#DCE6C4" },
  { label: "Total Fines", value: "₹4,850", icon: "Wallet", bg: "#5B6B2E" },
];

export const RECENT_BORROWED = [
  { user: "Rahul Sharma", email: "rahul@gmail.com", book: "Clean Code", author: "Robert C. Martin", borrowed: "20 May 2024", due: "03 Jun 2024", status: "Borrowed" },
  { user: "Priya Patel", email: "priya@gmail.com", book: "Atomic Habits", author: "James Clear", borrowed: "18 May 2024", due: "01 Jun 2024", status: "Borrowed" },
  { user: "Amit Verma", email: "amit@gmail.com", book: "The Alchemist", author: "Paulo Coelho", borrowed: "19 May 2024", due: "02 Jun 2024", status: "Borrowed" },
  { user: "Neha Singh", email: "neha@gmail.com", book: "Deep Work", author: "Cal Newport", borrowed: "21 May 2024", due: "04 Jun 2024", status: "Borrowed" },
  { user: "Vikram Joshi", email: "vikram@gmail.com", book: "Think and Grow Rich", author: "Napoleon Hill", borrowed: "17 May 2024", due: "31 May 2024", status: "Overdue" },
];

export const FINES_OVERVIEW = [
  { user: "Rahul Sharma", email: "rahul@gmail.com", amount: 250, status: "Unpaid" },
  { user: "Priya Patel", email: "priya@gmail.com", amount: 150, status: "Unpaid" },
  { user: "Amit Verma", email: "amit@gmail.com", amount: 300, status: "Paid" },
  { user: "Neha Singh", email: "neha@gmail.com", amount: 200, status: "Unpaid" },
  { user: "Vikram Joshi", email: "vikram@gmail.com", amount: 100, status: "Paid" },
];
